name: github actions pipeline
on:
  push:
    branches: 
    - 'main'
jobs:
  build_and_push_to_registry:
    name: Build and Push to repo
    runs-on: ubuntu-latest
    steps:
      - name: Check our repository
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push image
        run: |
          docker build -t rohitvuclip/nodejs-app:v2 .
          docker push rohitvuclip/nodejs-app:v2
      
